select * from CUSTOMER;

select * from ADDRESS;

select FIRST_NAME,LAST_NAME,ADDRESS,PHONE
from CUSTOMER join ADDRESS
on customer.ADDRESS_ID = ADDRESS.ADDRESS_ID;

--INNER JOIN ==> TAKES ONLY THE INTERSECTION
select FIRST_NAME,LAST_NAME,c.ADDRESS_ID,ADDRESS,PHONE
from CUSTOMER c join ADDRESS a
on c.ADDRESS_ID = a.ADDRESS_ID;

--LEFT JOIN ==> TAKES EVERYTHING FROM THE LEFT TABLE WHETHER THERE ARE COMMON VALUES OR NOT
select FIRST_NAME, LAST_NAME,c.ADDRESS_ID, ADDRESS, PHONE
from CUSTOMER c left join ADDRESS a
on c.ADDRESS_ID = a.ADDRESS_ID;

--RIGHT JOIN ==> TAKES EVERYTHING FROM THE RIGHT TABLE WHETHER THERE ARE COMMON VALUES OR NOT
select FIRST_NAME, LAST_NAME,c.ADDRESS_ID, ADDRESS, PHONE
from CUSTOMER c RIGHT join ADDRESS a
on c.ADDRESS_ID = a.ADDRESS_ID;

--FULL JOIN ==> TAKES EVERYTHING FROM THE RIGHT AND LEFT TABLE
select FIRST_NAME, LAST_NAME,c.ADDRESS_ID, ADDRESS, PHONE
from CUSTOMER c FULL join ADDRESS a
on c.ADDRESS_ID = a.ADDRESS_ID;